#pragma once

#include "misObjectRangeStr.h"
#include "serializable.h"

struct misVisualizationSetting : public Serializable
{
	misVisualizationSetting();

	virtual void serialize( XmlSerializer& s ) const;
	virtual void deserialize( XmlDeserializer& s );
	
	// Zoom factor of the slice generated from a 3D image. By default (zoom factor being 1), side length of the slice quad 
	// is equal to the diagonal of the image box. Modifying this value divides the default length of the image slice side by 
	// the specified factor.
	double GetImageSliceViewerZoomFactor() const;

	// Using this option, you can override the ImageSliceViewerZoomFactor option for displaying of CT images. It is understood 
	// that CT images usually need to be viewed with a greater zoom than MR images.
	double GetImageSliceViewerZoomFactorForCtImages() const;

	// Using this zoom factor only for special viewers were generated by panoramic curve that are tangential and cross sectional views
	double GetDentalSpecificViewsZoomFactor() const;
	double GetScrewTubeRadius() const { return m_ScrewTubeRadius; }
	void SetScrewTubeRadius(double val) { m_ScrewTubeRadius = val; }

	int    numberOfImagesShowInStandardModeForPreview;
	bool   useRayCastOnCameraChange;
	bool   ShowImageAnnotation;
	bool   RepresentationLoggerEnabled;
	double SkinThresholdForCT;
	double SkinThresholdForMRI;
	double SkinThresholdForMRT1;
	double SkinThresholdForMRT2;
	double BoneThresholdForCT;
	double TeethThresholdForCT;
	double MinPlaneOpacityForSettingWindowLevel;
	ObjectRangeListTypdef DefaultRangeList;

	bool ProstrateState;
	
private:
	double m_ImageSliceViewerZoomFactor;
	double m_ImageSliceViewerZoomFactorForCtImages;
	double m_DentalSpecificViewsZoomFactor;
	double m_ScrewTubeRadius = 1.0;

};
