#pragma once

#include "IVolumeSlicer.h"


MOCK_BASE_CLASS(MockVolumeSlicer, IVolumeSlicer)
{
	MOCK_NON_CONST_METHOD(SetControlToPan, 0, void());
	MOCK_NON_CONST_METHOD(UpdatePanMode, 0, void());
	MOCK_NON_CONST_METHOD(ResetContrast, 0, void());
	MOCK_NON_CONST_METHOD(SetInteractionMode, 1, void(INTERACTIONMODE mode));
	MOCK_NON_CONST_METHOD(SetImageStyle, 0, void());
	MOCK_NON_CONST_METHOD(SetDefaultWindowLevel, 0, void());
	MOCK_NON_CONST_METHOD(GetMeasurmentService, 0, misMeasurment*());
	MOCK_CONST_METHOD(GetInteractionState, 0, InteractionState());
	MOCK_NON_CONST_METHOD(SetInteractionState, 1, void(InteractionState val));
	MOCK_NON_CONST_METHOD(SetGeneralToolbarState, 1, void(const misGeneralToolbarState &generalToolbarState));
	MOCK_CONST_METHOD(GetGeneralToolbarState, 0, misGeneralToolbarState());
	MOCK_NON_CONST_METHOD(ResetGeneralToolbarState, 0, void());
	MOCK_NON_CONST_METHOD(ResetViewer, 0, void());
	MOCK_NON_CONST_METHOD(UpdateImage, 1, void(bool ));
	MOCK_NON_CONST_METHOD(GetImageRprensentaion, 0, std::shared_ptr<I2DRepresetation>());
	MOCK_NON_CONST_METHOD(UpdateImageInteractionState, 0, void());
	MOCK_NON_CONST_METHOD(ApplyOffset, 1, void(double offset));
	MOCK_NON_CONST_METHOD(CreateImageAnnotation, 0, void());
	MOCK_NON_CONST_METHOD(SetObliqueFlag, 1, void(bool isOblique));
	MOCK_NON_CONST_METHOD(SetOrientationDirection, 1, void(IMAGEORIENTATION newOrientation));
	MOCK_NON_CONST_METHOD(SetImageSliceViewerZoomFactor, 1, void(double zoomFactor));
	MOCK_NON_CONST_METHOD(ResetZoom, 0, void());
	MOCK_NON_CONST_METHOD(GetWidgetFocalPoint, 1, void(double[3]));
	MOCK_NON_CONST_METHOD(GetCameraService, 0, std::shared_ptr<misCameraInteraction>());
	MOCK_NON_CONST_METHOD(SetViewingProperties, 2, void(misPlaneEnum planeIndex, misWindowLevelStr winLevStr));
	MOCK_NON_CONST_METHOD(SetRealTimeMode, 1, void(bool val));
	MOCK_CONST_METHOD(GetRealTimeMode, 0, bool());
	MOCK_NON_CONST_METHOD(CheckFlyZone, 1, void(const std::string& segmentationRegion));
	MOCK_CONST_METHOD(GetCornerProperties, 0, std::shared_ptr<ICornerProperties> () );
	MOCK_NON_CONST_METHOD(GetLandmarkPosition, 1, double*(int index) );
	MOCK_NON_CONST_METHOD(SetCurrentLandmarkType, 1,void(misLandmarkType) );
	MOCK_NON_CONST_METHOD(GetScrewWidgetService, 1, std::shared_ptr<IScrewCompound> (misUID uid) );
	MOCK_NON_CONST_METHOD(LockAllScrews, 0,void () );
	MOCK_NON_CONST_METHOD(GetRenderer,0,  vtkRenderer* () );
	MOCK_NON_CONST_METHOD(GetCursorService, 0, std::shared_ptr<ICursorService> () );
	MOCK_NON_CONST_METHOD(OnScrew, 1, void (misUID screwUID) );
	MOCK_NON_CONST_METHOD(InvokeEvent, 1, void (const itk::EventObject& event) );
	MOCK_NON_CONST_METHOD(ShowAnnotationDetailOn, 0, void () );
	MOCK_NON_CONST_METHOD(ShowAnnotationDetailOff, 0, void () );
	MOCK_NON_CONST_METHOD(SetShowAnnotationDetail, 1, void (bool status) );
	MOCK_CONST_METHOD(ShowAnnotationDetail, 0,  bool ()  );
	MOCK_NON_CONST_METHOD(GetMainRepresentation, 0, std::shared_ptr<IRepresentation>  () );
	MOCK_NON_CONST_METHOD(AddObserver, 2, unsigned long (const itk::EventObject & event, itk::Command *command) );
	MOCK_CONST_METHOD(HasObserver,1,  bool (const itk::EventObject & )  );
	MOCK_NON_CONST_METHOD (GetNumberOfRepresentations, 0, int () );
	MOCK_NON_CONST_METHOD (GetImageCallBack, 0, misImageCallback* () );
	MOCK_NON_CONST_METHOD (Render, 0, void () );
	MOCK_CONST_METHOD (GetOrientationDirection, 0, IMAGEORIENTATION () );
	MOCK_NON_CONST_METHOD (ReleaseImageResource, 0, void () );
	MOCK_NON_CONST_METHOD (AddRepresentation, 1, void (std::shared_ptr<IRepresentation> pRepresentation) );
	MOCK_NON_CONST_METHOD (UpdateWindowSize, 1, void (misStrctWindowSize& size) );
	MOCK_NON_CONST_METHOD (RemoveRepresentation, 1,void (std::shared_ptr<IRepresentation> pRepresent) );
	MOCK_NON_CONST_METHOD (ProcessRequest, 1, bool (const itk::EventObject*) );
	MOCK_NON_CONST_METHOD (AddImageOrientation3DModel, 1, void (std::shared_ptr<IRepresentation> ) );
	MOCK_CONST_METHOD (GetWindow, 0,std::shared_ptr<Iwindows> ()  );	// Gets the render window ).
	MOCK_NON_CONST_METHOD(AddNextLandmark, 3, int	(const double*, misLandmarkType,LANDMARKLABLETYPE) );
	MOCK_NON_CONST_METHOD(AddLandmark, 4, void (int , const double*, misLandmarkType ,	LANDMARKLABLETYPE ));
	MOCK_NON_CONST_METHOD(AddOrSetNextLandmark, 4, void(int, const double*, misLandmarkType, LANDMARKLABLETYPE), AddOrSetNextLandmark_1);
	MOCK_NON_CONST_METHOD(AddOrSetNextLandmark, 3, int(const double*, misLandmarkType, LANDMARKLABLETYPE), AddOrSetNextLandmark_2);
	MOCK_NON_CONST_METHOD(GetROICompressData, 0,  double * () );
	MOCK_NON_CONST_METHOD(DeleteAllScrews, 0,void () );
	MOCK_CONST_METHOD(Get3DViewer, 0, std::shared_ptr<I3DViewer> () );
	MOCK_CONST_METHOD(GetTypeDirection,0,  misViewerTypeDirection (void)  );
	MOCK_NON_CONST_METHOD(ChangeMeasurmentMode, 1, bool (MEASURMENTMODE ) );
	MOCK_NON_CONST_METHOD(HideLandmarks, 0, void());
	MOCK_NON_CONST_METHOD(SetMainRepresentation, 2, void(std::shared_ptr<IRepresentation> , IMAGEORIENTATION) );
	MOCK_NON_CONST_METHOD(MakeCurrentRenderer, 0, void());
	MOCK_NON_CONST_METHOD(SetViewPort, 1, void(const misViewPort&));
	MOCK_NON_CONST_METHOD(RemoveRepresentationByName, 1, void(std::string name));
	MOCK_NON_CONST_METHOD(InitializeWidget, 2, void(misCursorType widgetType, double));
	MOCK_NON_CONST_METHOD(SetShowManModel, 1, void(bool val));
	MOCK_NON_CONST_METHOD(ResetLandMarks, 0, void(void), identifier_16);
	MOCK_NON_CONST_METHOD(ResetLandMarks, 1, void(misLandmarkType lndType), identifier_4);
	MOCK_NON_CONST_METHOD(InvalidateLandmark, 1, void(int index));
	MOCK_NON_CONST_METHOD(SetCurrentLandmark, 2, void(misLandmarkType, int));
	MOCK_NON_CONST_METHOD(SetCurrentLandmarkLableType, 1, void(LANDMARKLABLETYPE val));
	MOCK_NON_CONST_METHOD(SetDentalSurgeryType, 1, void(DentalSurgeryType));
	MOCK_NON_CONST_METHOD(DeleteScrew, 1, void(misUID screwUID));
	MOCK_NON_CONST_METHOD(HighlightScrew, 2, void(misUID screwUID, bool highlight));
	MOCK_NON_CONST_METHOD(SetROI, 1, void(misROI data), identifier_6);
	MOCK_NON_CONST_METHOD(ResetROI, 0, void());
	MOCK_NON_CONST_METHOD(ROIWidgetActivation, 1, void(bool activation));
	MOCK_NON_CONST_METHOD(SetDentalSpecialViewsEnable, 1, void(bool enabled));
	MOCK_NON_CONST_METHOD(SetPanoramicCoordinateConverter, 1, void(std::shared_ptr<const IPanoramicCoordinatesConverter> coordinateConverter));
	MOCK_NON_CONST_METHOD(SetCaptureLandmarkFlag, 1, void(bool val));
	MOCK_NON_CONST_METHOD(SetUpdateLandmarkFlag, 1, void(bool val));
	MOCK_NON_CONST_METHOD(SetCurrentLandmarkIndex, 1, void(int val));
	MOCK_NON_CONST_METHOD(OffScrew, 1, void(misUID screwUID));
	MOCK_NON_CONST_METHOD(RemoveAllScrewServices, 0, void());
	MOCK_NON_CONST_METHOD(InitializeScrewWidget, 2, void(misScrewWidgetData, IMAGEORIENTATION), id_2);
	MOCK_NON_CONST_METHOD(RemoveLandMarkRepresentations, 0, void());
	MOCK_NON_CONST_METHOD(GetLandmarkList, 0, LandmarkListType(void), identifier_15);
	MOCK_NON_CONST_METHOD(GetLandmarkList, 1, misSimplePointListType(misLandmarkType seedType), identifier_3);
	MOCK_NON_CONST_METHOD(SetToolPosition, 3, void(double xCoord, double yCoord, double zCoord));
	MOCK_NON_CONST_METHOD(HasRepresentationByName, 1, bool(const std::string& name));
	MOCK_NON_CONST_METHOD(SetToolTransform, 1, void(std::shared_ptr<ITransform> transform));
	MOCK_NON_CONST_METHOD(AddCoordinateSytemRenderer, 1, void(std::shared_ptr<ICoordinateSystemRenderer> coordianteRenderer));
	MOCK_NON_CONST_METHOD(GetLandmarkPosition, 2, double*(int index, misLandmarkType category), identifier_2);
	MOCK_NON_CONST_METHOD(GetSeedBounding, 2, misROI (int* dimenstion, double* spacing));
	MOCK_NON_CONST_METHOD(Reset, 0, void());
	MOCK_NON_CONST_METHOD(SetState, 1, void(int val));
	MOCK_NON_CONST_METHOD(BackToPanModeByRightClick, 0, void());
	MOCK_NON_CONST_METHOD(UpdateImageWithSelectedPoint, 0, void());
	MOCK_NON_CONST_METHOD(AddPointSelectObserver, 1,  void (std::pair<unsigned long, vtkSmartPointer<vtkCommand>>) );
};
